haskellPackages:
  with haskellPackages;
    [
      ansi-terminal
      async
      base
      bytestring
      containers
      conduit
      conduit-extra
      data-fix
      dhall
      filepath
      pretty-simple
      recursion-schemes
      string-conversions
      stm-conduit
      tasty
      tasty-golden
      text
      typed-process
      unix
    ]
