haskellPackages:
  with haskellPackages;
    [
      ansi-terminal
      base
      bytestring
      containers
      data-fix
      dhall
      filepath
      freer-simple
      pretty-simple
      recursion-schemes
      string-conversions
      tasty
      tasty-golden
      text
      typed-process
      unix
    ]
