[scripts.setup-pgdata]
help = "Setup postgres"
script = '''
#!/bin/bash
set -efu
if [[ ! -d "$PGDATA" ]]; then
    initdb
    cat >> "$PGDATA/postgresql.conf" <<-EOF
        listen_addresses = ''
        unix_socket_directories = '$PGHOST'
EOF
    echo "CREATE DATABASE $USER;" | postgres --single -E postgres
fi
'''

[services.db]
command = ["/usr/bin/postgres", "-D", "db"]
exec-before = ["setup-pgdata"]
