[env]
PGDATA = "/home/duijf/repos/laps/ignore/db"
PGHOST = "/home/duijf/repos/laps/ignore/db/sock"

[scripts.check]
help = "Run `cargo check` on file change"
script = '''
#!/bin/bash
fd -t f -e rs | entr cargo check
'''

[scripts.build]
help = "Run `cargo build` on file change"
script = '''
#!/bin/bash
fd -t f -e rs | entr cargo build
'''

[scripts.setup-pgdata]
help = "Setup postgres"
script = '''
#!/bin/bash
set -efu
if [[ ! -d "$PGDATA" ]]; then
    initdb
    cat >> "$PGDATA/postgresql.conf" <<-EOF
        listen_addresses = ''
        unix_socket_directories = '$PGHOST'
EOF
    echo "CREATE DATABASE $USER;" | postgres --single -E postgres
fi
'''

[services.db]
command = ["/usr/bin/postgres", "-D", "db"]
exec-before = ["setup-pgdata"]
