[environment]
PGDATA = "/home/duijf/repos/laps/ignore/db"
PGHOST = "/home/duijf/repos/laps/ignore/db/sock"

[watches.check]
description = "Run `cargo check` on file change"
exec = ["cargo", "check"]
file-types = ["rs"]

[watches.build]
description = "Run `cargo build` on file change"
exec = ["cargo", "build"]
file-types = ["rs"]

[services.db]
description = "Run Postgres"
exec = ["postgres"]
wants = ["db-setup"]

[commands.db-setup]
description = "Create development DB"
exec-script = '''
#!/bin/bash
set -efu
if [[ ! -d "$PGDATA" ]]; then
    initdb
    mkdir $PGDATA/sock/
    cat >> "$PGDATA/postgresql.conf" <<-EOF
        listen_addresses = ''
        unix_socket_directories = '$PGHOST'
EOF
    echo "CREATE DATABASE $USER;" | postgres --single -E postgres
fi
'''

[commands.db-remove]
description = "Remove development DB"
exec = ["rm", "-rf", "$PGDATA"]

[commands.doc]
description = "Get all docs"
exec-script = '''
#!/bin/bash
cargo doc --open
rustup doc --std
'''
